#ifndef VOIDCOIN_CHAINPARAMSSEEDS_H
#define VOIDCOIN_CHAINPARAMSSEEDS_H
/**
 * List of fixed seed nodes for the voidcoin network
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Each line contains a BIP155 serialized (networkID, addr, port) tuple.
 */
static const uint8_t chainparams_seed_main[] = {
    0x01,0x04,0x2e,0x07,0x07,0x71,0x61,0x1e,
};
static const uint8_t chainparams_seed_signet[] = {
    0x01,0x04,0x2e,0x07,0x07,0x71,0x61,0x1e,
};
#endif // VOIDCOIN_CHAINPARAMSSEEDS_H
